function y = preprocess(x,tx)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 27-Feb-2024 15:17:44

Fs = 1/mean(diff(tx)); % Average sample rate
y = bandpass(x,[25 450],Fs,'Steepness',0.85,'StopbandAttenuation',60);

y = bandstop(y,[49 51],Fs,'Steepness',0.85,'StopbandAttenuation',60);

windowLength = 400; %Value converted to samples
[y,~] = envelope(y,windowLength,'rms');

y = smoothdata(y,'movmedian','SamplePoints',tx');
